### ISSUE TITLE
Support Cucumber 3.0

### ISSUE THREAD

**Issue by jchristi** [Wallaceh/cukeforker#22]
`Scenario` and `ScenarioList` classes don't appear to work with the new Cucumber 3.0
```
NoMethodError: undefined method 'reverse' for #<ScenarioList:0x0000000326c958>
/root/.bundler/ruby/2.3.0/gems/cucumber-core-3.0.0/lib/cucumber/core.rb:37:in 'compose'
/root/.bundler/ruby/2.3.0/gems/cucumber-core-3.0.0/lib/cucumber/core.rb:19:in 'compile'
/root/.bundler/ruby/2.3.0/gems/cucumber-core-3.0.0/lib/cucumber/core.rb:14:in 'execute'
/root/.bundler/ruby/2.3.0/gems/cukeforker-1.1.0/lib/cukeforker/scenarios.rb:23:in 'block in tagged'
/root/.bundler/ruby/2.3.0/gems/cukeforker-1.1.0/lib/cukeforker/scenarios.rb:20:in 'each'
/root/.bundler/ruby/2.3.0/gems/cukeforker-1.1.0/lib/cukeforker/scenarios.rb:20:in 'tagged'
/root/.bundler/ruby/2.3.0/gems/cukeforker-1.1.0/lib/cukeforker/scenarios.rb:10:in 'by_args'
```
I was able to get past that error by adding reverse and reduce methods to `ScenarioList` but then I got the following error:
```
NoMethodError: undefined method `test_case_started' for #<Array:0x0055d284424058>
/root/.bundler/ruby/2.1.0/gems/cucumber-core-3.0.0/lib/cucumber/core/test/runner.rb:18:in `test_case'
```
